# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'map_search.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CreateMap = QtWidgets.QPushButton(self.centralwidget)
        self.CreateMap.setGeometry(QtCore.QRect(50, 140, 591, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CreateMap.setFont(font)
        self.CreateMap.setObjectName("CreateMap")
        self.MapLab = QtWidgets.QLabel(self.centralwidget)
        self.MapLab.setGeometry(QtCore.QRect(50, 220, 591, 371))
        self.MapLab.setText("")
        self.MapLab.setObjectName("MapLab")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.TextX = QtWidgets.QTextEdit(self.centralwidget)
        self.TextX.setGeometry(QtCore.QRect(60, 10, 101, 31))
        self.TextX.setObjectName("TextX")
        self.TextY = QtWidgets.QTextEdit(self.centralwidget)
        self.TextY.setGeometry(QtCore.QRect(290, 10, 101, 31))
        self.TextY.setObjectName("TextY")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.TextScale = QtWidgets.QTextEdit(self.centralwidget)
        self.TextScale.setGeometry(QtCore.QRect(530, 10, 101, 31))
        self.TextScale.setObjectName("TextScale")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(520, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Map Search"))
        self.CreateMap.setText(_translate("MainWindow", "Create a map"))
        self.label.setText(_translate("MainWindow", "Position de x"))
        self.label_3.setText(_translate("MainWindow", "Position de y"))
        self.label_2.setText(_translate("MainWindow", "Scale"))
